# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/rawan/FINAL_XADC/FINAL_XADC.srcs/sources_1/ip/cordic_1/cordic_1.xci
# IP: The module: 'cordic_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rawan/FINAL_XADC/FINAL_XADC.gen/sources_1/ip/cordic_1/cordic_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/rawan/FINAL_XADC/FINAL_XADC.srcs/sources_1/ip/cordic_1/cordic_1.xci
# IP: The module: 'cordic_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rawan/FINAL_XADC/FINAL_XADC.gen/sources_1/ip/cordic_1/cordic_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
