set_property SRC_FILE_INFO {cfile:{C:/Different/SRIP_2024/Photonics lab/Lock-in amplifier/FINAL_XADC/FINAL_XADC.srcs/constrs_1/new/XADC.xdc} rfile:../FINAL_XADC.srcs/constrs_1/new/XADC.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets clk_IBUF_BUFG]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {coswave_reg__0[1]}]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {coswave_reg__0[6]}]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {coswave_reg__0[7]}]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {coswave_reg__0[8]}]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {coswave_reg__0[9]}]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {coswave_reg__0[10]}]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {coswave_reg__0[0]}]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {coswave_reg__0[2]}]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {coswave_reg__0[3]}]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {coswave_reg__0[4]}]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {coswave_reg__0[5]}]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {coswave_reg__0[11]}]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {sinusoidal_reg__0[0]}]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {sinusoidal_reg__0[1]}]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {sinusoidal_reg__0[2]}]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {sinusoidal_reg__0[3]}]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {sinusoidal_reg__0[4]}]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {sinusoidal_reg__0[5]}]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {sinusoidal_reg__0[7]}]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {sinusoidal_reg__0[10]}]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {sinusoidal_reg__0[6]}]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {sinusoidal_reg__0[8]}]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {sinusoidal_reg__0[9]}]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {sinusoidal_reg__0[11]}]
set_property src_info {type:XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {x_12bit[0]}]
set_property src_info {type:XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {x_12bit[1]}]
set_property src_info {type:XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {x_12bit[3]}]
set_property src_info {type:XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {x_12bit[4]}]
set_property src_info {type:XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {x_12bit[9]}]
set_property src_info {type:XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {x_12bit[10]}]
set_property src_info {type:XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {x_12bit[2]}]
set_property src_info {type:XDC file:1 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {x_12bit[5]}]
set_property src_info {type:XDC file:1 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {x_12bit[6]}]
set_property src_info {type:XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {x_12bit[7]}]
set_property src_info {type:XDC file:1 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {x_12bit[8]}]
set_property src_info {type:XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {x_12bit[11]}]
set_property src_info {type:XDC file:1 line:336 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {x_12bit[0]} {x_12bit[1]} {x_12bit[2]} {x_12bit[3]} {x_12bit[4]} {x_12bit[5]} {x_12bit[6]} {x_12bit[7]} {x_12bit[8]} {x_12bit[9]} {x_12bit[10]} {x_12bit[11]}]]
set_property src_info {type:XDC file:1 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[27]}]
set_property src_info {type:XDC file:1 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[32]}]
set_property src_info {type:XDC file:1 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[36]}]
set_property src_info {type:XDC file:1 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[41]}]
set_property src_info {type:XDC file:1 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[45]}]
set_property src_info {type:XDC file:1 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[26]}]
set_property src_info {type:XDC file:1 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[24]}]
set_property src_info {type:XDC file:1 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[28]}]
set_property src_info {type:XDC file:1 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[33]}]
set_property src_info {type:XDC file:1 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[37]}]
set_property src_info {type:XDC file:1 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[40]}]
set_property src_info {type:XDC file:1 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[42]}]
set_property src_info {type:XDC file:1 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[44]}]
set_property src_info {type:XDC file:1 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[25]}]
set_property src_info {type:XDC file:1 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[29]}]
set_property src_info {type:XDC file:1 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[31]}]
set_property src_info {type:XDC file:1 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[35]}]
set_property src_info {type:XDC file:1 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[38]}]
set_property src_info {type:XDC file:1 line:450 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[46]}]
set_property src_info {type:XDC file:1 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[47]}]
set_property src_info {type:XDC file:1 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[30]}]
set_property src_info {type:XDC file:1 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[34]}]
set_property src_info {type:XDC file:1 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[39]}]
set_property src_info {type:XDC file:1 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {fir1/m_axis_data_tdata[43]}]
set_property src_info {type:XDC file:1 line:472 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {m5/P[0]} {m5/P[1]} {m5/P[2]} {m5/P[3]} {m5/P[4]} {m5/P[5]} {m5/P[6]} {m5/P[7]} {m5/P[8]} {m5/P[9]} {m5/P[10]} {m5/P[11]} {m5/P[12]} {m5/P[13]} {m5/P[14]} {m5/P[15]} {m5/P[16]} {m5/P[17]} {m5/P[18]} {m5/P[19]} {m5/P[20]} {m5/P[21]} {m5/P[22]} {m5/P[23]} {m5/P[24]} {m5/P[25]} {m5/P[26]} {m5/P[27]} {m5/P[28]} {m5/P[29]} {m5/P[30]} {m5/P[31]} {m5/P[32]}]]
set_property src_info {type:XDC file:1 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {out[11]}]
set_property src_info {type:XDC file:1 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {out[10]}]
set_property src_info {type:XDC file:1 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {out[9]}]
set_property src_info {type:XDC file:1 line:480 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {out[8]}]
set_property src_info {type:XDC file:1 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {out[8]}]
set_property src_info {type:XDC file:1 line:482 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T15 [get_ports {out[9]}]
set_property src_info {type:XDC file:1 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U14 [get_ports {out[10]}]
set_property src_info {type:XDC file:1 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports {out[11]}]
set_property src_info {type:XDC file:1 line:547 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {out_OBUF[9]}]
set_property src_info {type:XDC file:1 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {out_OBUF[11]}]
set_property src_info {type:XDC file:1 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {out_OBUF[8]}]
set_property src_info {type:XDC file:1 line:550 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {out_OBUF[10]}]
set_property src_info {type:XDC file:1 line:853 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {do_out[1]}]
set_property src_info {type:XDC file:1 line:854 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {do_out[3]}]
set_property src_info {type:XDC file:1 line:857 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {do_out[0]}]
set_property src_info {type:XDC file:1 line:862 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {do_out[2]}]
set_property src_info {type:XDC file:1 line:871 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {out_OBUF[0]}]
set_property src_info {type:XDC file:1 line:872 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {out_OBUF[1]}]
set_property src_info {type:XDC file:1 line:873 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {out_OBUF[2]}]
set_property src_info {type:XDC file:1 line:874 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {out_OBUF[3]}]
set_property src_info {type:XDC file:1 line:875 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {out_OBUF[4]}]
set_property src_info {type:XDC file:1 line:876 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {out_OBUF[5]}]
set_property src_info {type:XDC file:1 line:877 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {out_OBUF[6]}]
set_property src_info {type:XDC file:1 line:878 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {out_OBUF[7]}]
set_property src_info {type:XDC file:1 line:891 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:892 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:893 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:894 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:895 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:896 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:897 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:898 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:899 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:900 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:901 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property src_info {type:XDC file:1 line:902 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:903 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:904 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {m1/A[0]} {m1/A[1]} {m1/A[2]} {m1/A[3]} {m1/A[4]} {m1/A[5]} {m1/A[6]} {m1/A[7]} {m1/A[8]} {m1/A[9]} {m1/A[10]} {m1/A[11]}]]
set_property src_info {type:XDC file:1 line:905 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:906 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:907 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:908 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {out_OBUF[0]} {out_OBUF[1]} {out_OBUF[2]} {out_OBUF[3]} {out_OBUF[4]} {out_OBUF[5]} {out_OBUF[6]} {out_OBUF[7]}]]
set_property src_info {type:XDC file:1 line:909 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:910 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:911 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:912 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
